### ISSUE TITLE
文件头是注释并且已经用了define

### ISSUE THREAD

**Issue by jianrongjia** [fex-team/fis-postprocessor-jswrapper#11]
能在下面的if这里加个注释判断吗/*_/ 和 //
类似requirejs干掉注释的正则
commentRegExp = /(\/\_([\s\S]_?)\_\/|([^:]|^)\/\/(.*)$)/mg,

要不然已经自定义的define文件里，头几行都不敢写注释了，写了define还会被包一个define
            if (!/^\s_define\s_(/.test(content)) {
                content = 'define(\'' + file.getId() + '\', function(require, exports, module){ ' + content +
                    ' \r\n});';
            }

**Comment by hefangshi** [comment]
关于这个 define ，我们尝试过修改为一个更合理的配置，但是发现会影响现有代码的运行，因此建议如果你有特殊需求，重新弄一个符合你期望的jswrapper插件吧。

**Comment by jianrongjia** [comment]
OK
